### ISSUE TITLE
Summary Enhancements

### ISSUE THREAD

**Issue by Vanethir** [finndev/PokeBuddy#172]
Since there is such a huge input of enhancements _(you guys are awesome)_ I will keep a list here! :)

There are so many duplicates as well as new ideas. So it's to ensure we keep track of all this enhancements mentioned in different threads: (Transfer Pokemon not working yet, but will hopefully be fixed soon.)

**Pokemon:**
- [ ] Set amount of Pokemon (of each kind) #10 
- [ ] Transfer Pokemon below CP #10, #48, #76, #158 
- [ ] Show IV% #128 
- [ ] Transfer- & Evolutionoptions for IV% #36, #82, #93, #115 
- [ ] Evolution of best Pokemon first #10, #79, #115 
- [ ] Evolution (with afterevolution CP calculation) #76, #128 
- [ ] Transfer- & Evolutionfilter for Movesets #36 
- [ ] Manually transfer/evolve Pokemon via PokeBuddy #48 
- [ ] show Pokemonstats in PokeBuddy #48, #52 
- [ ] Hunt specific Pokemon (ignore list) #48 
- [ ] Add numbers to Pokemon transfer (amount you want to keep) #126, #128 
- [ ] show list of transfered/evolved Pokemon #132, #144 
- [ ] Select all for Transfer/Evolution #133

**Items:**
- [ ] Use different Pokeballs for increased % #45, #76, #82, #94, #128

**Mapping:**
- [ ] Set max distance to starting location #38, #48 
- [ ] Pathfinding without Pokestops #48, #68, #169 
- [ ] Search Pokemon (Pokevision feature) #48 
- [ ] GPX pathing #48, #86 

**Other:**
- [ ] Automatic Incubation #13, #48, #76, #107, #115, #128 
- [ ] Option for Incense usage #20, #31, #128 
- [ ] Randomize your throws #50, #163 
- [ ] Soft Ban Unbanner #76, #82, #128 
- [ ] Multiaccounting Features #86, #115 
- [ ] Multilanguage #90 
- [ ] Update Button #94 
- [ ] Coordinate list with Pokemon Hotspots #115 
- [ ] Changelog #115, 128
- [ ] Timestamps to start/stop PokeBuddy #125 
- [ ] Show PokeBuddy version in options #128 
- [ ] Minimize/Maximize GUI Button #128 
- [ ] save last location (for restart/crash) #128 
- [ ] Exportable file for event logging #155

**Comment by therealpequod** [comment]
Oh god this is awesome! Thanks a lot for all your work :) !!!

**Comment by Thrallix** [comment]
Vanethir, would you please add me on skype; Waddafoock?
I'd like to do a small proposition.

**Comment by epicrean** [comment]
Implemting something like Poke Radar.  What I mean is let users specifiy what Pokémon they want to catch only, this is in other bots, then connecting to a service like poke radar or build the same idea into Poke Buddy so the bot knows where to send the user to capture Pokémon.

Implementing what Poke Radar should be relatively simple since the bot is already capturing the information.  Poke Radar allows users who spot Pokémon in the wild to tag them, then other users of the app see the pokemon and can go over and get it.

**Comment by Fenderfix** [comment]
II want to propose the possibility of choose which Pokémon capture or not :)

**Comment by PDeception** [comment]
> Fenderfix commented an hour ago
II want to propose the possibility of choose which Pokémon capture or not :)

There is already this option, in the settings file, you can choose which pokemon to avoid and not catch.

**Comment by curtiola** [comment]
Nice, thanks Vanethir :D I like what I see

**Comment by Fenderfix** [comment]
@PDeception I found the "PokemonNotToCatch": null , but I need to put the number of Pokédex or the name? Anyway, I would prefer this option on the BOT ;)

**Comment by curtiola** [comment]
@Fenderfix have you tried adding pokemon in the same format as the evolve selected section in the settings? i'm not sure if it's possible but i will try later when i have more time

**Comment by killer2318** [comment]
Can we add a function like using other pokeball(greatball,ultraball) when there is no pokeball(red one)

**Comment by Vanethir** [comment]
@killer2318 It's currently a bug. It should always do this. 

@Fenderfix @curtiola I don't think it's implemented yet. Once I know it is, I will inform you and it will most likely be part of the GUI. :)

@epicrean Should be "Search Pokemon (Pokevision feature)" :)

**Comment by IamDeric** [comment]
GUI: possible to resize or full screen gui, aside from minimize/maximize.
Color coded log, specific color for

**Comment by IamDeric** [comment]
Specific color for errors and catch, items, etc

**Comment by IAmYawz** [comment]
Has been updated a few minutes ago, what's new?

**Comment by futi666** [comment]
wow awesome, thank you all for ur hardwork!!!
greetings from austria

**Comment by isoueu** [comment]
Great, more goods sugestions in #546

**Comment by curtiola** [comment]
Any progress on this? "Add numbers to Pokemon transfer (amount you want to keep) #10, #126, #128 , #198 "
I'm excited for this one xD

**Comment by Neshira** [comment]
I too am very excited for the changes in transferring pokemon. As of now I always keep it unchecked because it keeps transferring every pokemon but the strongest. It makes for some serious manual transferring after though! I'd love to be able to set it to transfer only pokemon under a certain CP. Or even just having the current system fixed would rock.

**Comment by Neshira** [comment]
Maybe a feature to choose pokemon you don't want to catch? I definitely don't need any more pidgeys or ratattas.

**Comment by curtiola** [comment]
It's already on the list luckily

**Comment by Neshira** [comment]
Awesome! I don't mind the stardust but like maybe an auto transfer all pidgeys...I dunno. I guess if the transfer option was working correctly it would take care of that honestly. Otherwise this is such a great thing. It's none of my business why anyone else uses this program but I use it because I live in a very rural area. There aren't any pokestops within a hundred miles and we only go into the city once or twice a month. Using this program just for like a few minutes a day allows me to have pokeballs, berries and such when I go into the city and can actually catch pokemon. It also gives me a chance at some of the low level gyms in the city.

**Comment by RayTwente** [comment]
awesome! Thanks a lot for all your work :)

**Comment by TFSho** [comment]
@Vanethir 
Favor: any way you could put in the current build version above the check boxes in the OP next time you edit? just to make sure we're all on the same page

**Comment by DatFIXER** [comment]
I want to add (could be a duplicate, idk):
- Give the bot more humanity, simulating the fail sometimes (i mean sometimes a pokemon could just flee but i mean most of the time the bot uses only 1 pokeball and get 210exp, that means he throw curved ball and get excellent...seems too much "efficient" for my thoughs)

**Comment by Ray-PoGo-NL** [comment]
![naamloos](https://cloud.githubusercontent.com/assets/20781652/17586087/db3c5540-5fbf-11e6-9d54-823b5ca2c242.png)
After yesterday blocked on many ip's
so i see it resolved

I think
o'ja something else
I found out as a go 35km you will become the fog blocked access
does not always turn on the egg if you have nothing they see that you have a bot running

**Comment by EranAvidor** [comment]
Hi there @EloBuddyLtd @finndev , thanks for all the effort you guys put in this tool.
Do you have any prioritised task list?
A huge usability enhancement could be just showing the full pokemon's stats (including IVs of course) and a manual transfer option.
In addition is there anyway we can contribute to your project?
